Use WinAPI to simulate pointermovements
H-M-H/Weylus pull request #128
Opened 2021-11-25 18:38 UTC by qdlmcfresh

Add pen support for #17 
Touch is not implemented yet.
Since the coordinates sent by the event are not padded to fit the actual monitorlayout on a multimonitor setup, the pointer will allways be on the leftmost monitor.

The library [captrs](https://docs.rs/captrs/) supports taking screenshots of multiple monitors, so this could be used instead of autopilot. 

To get the number of connected and active displays this can be used. 
```rust
use winapi::um::winuser::*;
use winapi::um::wingdi::{DISPLAY_DEVICEA, DISPLAY_DEVICE_ACTIVE};
fn get_connected_monitors() -> i32 {
    let mut i = 0u32;
    let mut connected_monitors = 0;
    unsafe {
        let mut dsp_dev: DISPLAY_DEVICEA = std::mem::zeroed();
        dsp_dev.cb = std::mem::size_of::<DISPLAY_DEVICEA>() as u32;
        while EnumDisplayDevicesA(
            std::ptr::null(),
            i,
            std::ptr::addr_of_mut!(dsp_dev),
            EDD_GET_DEVICE_INTERFACE_NAME,
        ) != 0
        {
            if dsp_dev.StateFlags & DISPLAY_DEVICE_ACTIVE != 0 {
                connected_monitors += 1;
            }
            i += 1;
        }
    }
    connected_monitors as i32
}
```

2021-11-25 19:06 UTC, H-M-H commented
> The library captrs supports taking screenshots of multiple monitors, so this could be used instead of autopilot.

Hmm, how does captrs work, it looks like you can pass some kind of ID to new: https://docs.rs/captrs/0.3.1/captrs/struct.Capturer.html#method.new, how does it map to monitors?

Regarding your implementation, it's better not to modify `src/input/autopilot_device.rs` as it's still required for macOS but instead create a new file say ` src/input/winapi_device.rs` that implements https://github.com/H-M-H/Weylus/blob/e23d3b9133abbe7e43e27b15aecfa436158b8033/src/input/device.rs#L10-L16 and then instantiate it here: https://github.com/H-M-H/Weylus/blob/e23d3b9133abbe7e43e27b15aecfa436158b8033/src/websocket.rs#L513-L517

2021-11-25 19:15 UTC, qdlmcfresh commented
> > The library captrs supports taking screenshots of multiple monitors, so this could be used instead of autopilot.
> 
> Hmm, how does captrs work, it looks like you can pass some kind of ID to new: https://docs.rs/captrs/0.3.1/captrs/struct.Capturer.html#method.new, how does it map to monitors?
> 
Yep the id is the monitor nr. 0 is the primary
> Regarding your implementation, it's better not to modify `src/input/autopilot_device.rs` as it's still required for macOS but instead create a new file say ` src/input/winapi_device.rs` that implements
> 
> https://github.com/H-M-H/Weylus/blob/e23d3b9133abbe7e43e27b15aecfa436158b8033/src/input/device.rs#L10-L16
> and then instantiate it here:
> 
> https://github.com/H-M-H/Weylus/blob/e23d3b9133abbe7e43e27b15aecfa436158b8033/src/websocket.rs#L513-L517

yep will do that this was just for fast testing

2021-11-25 20:07 UTC, H-M-H commented
> Yep the id is the monitor nr. 0 is the primary

That's nice, implementing a capturable should be straight forward then. There is a Capturable trait:
https://github.com/H-M-H/Weylus/blob/e23d3b9133abbe7e43e27b15aecfa436158b8033/src/capturable/mod.rs#L33-L47
and a Recorder trait
https://github.com/H-M-H/Weylus/blob/e23d3b9133abbe7e43e27b15aecfa436158b8033/src/capturable/mod.rs#L16-L18
that need to be implemented. Have a look at https://github.com/H-M-H/Weylus/blob/master/src/capturable/autopilot.rs for the most basic Capturable + Recorder. You could add a new captrs capturable that stores its monitor id. As captrs returns a &[] to
```rust
#[repr(C)]
pub struct Bgr8 {
    pub b: u8,
    pub g: u8,
    pub r: u8,
    _pad: u8,
}
```
(using `capture_store_frame` and `get_stored_frame`) it can be safely transmuted to a &[u8] with BGRx layout, which is fortunately exactly what Weylus uses internally as well. Finally the capturables need to be instantiated here: https://github.com/H-M-H/Weylus/blob/e23d3b9133abbe7e43e27b15aecfa436158b8033/src/capturable/mod.rs#L55.

> yep will do that this was just for fast testing

Alright!

2021-11-26 00:59 UTC, qdlmcfresh commented
My capturer implementation doesnt compile. Dont really know what to do about that. Its my first time really using rust ...
```rust
use crate::capturable::{Capturable, Recorder};
use captrs::Capturer;
use std::boxed::Box;
use std::error::Error;

#[derive(Clone)]
pub struct CaptrsCapturable {
    id: u8,
    capturer: Capturer,
}

impl CaptrsCapturable {
    pub fn new(id: u8) -> CaptrsCapturable {
        let capturer = Capturer::new(id).unwrap();
        CaptrsCapturable { id, capturer }
    }
}

impl Capturable for CaptrsCapturable {
    fn name(&self) -> String {
        "Desktop (captrs)".into()
    }
    fn geometry_relative(&self) -> Result<(f64, f64, f64, f64), Box<dyn Error>> {
        Ok((0.0, 0.0, 1.0, 1.0))
    }
    fn before_input(&mut self) -> Result<(), Box<dyn Error>> {
        Ok(())
    }
    fn recorder(&self, _capture_cursor: bool) -> Result<Box<dyn Recorder>, Box<dyn Error>> {
        Ok(Box::new(CaptrsRecorder::new()))
    }
}

pub struct CaptrsRecorder {
    img: Vec<u8>,
}

impl CaptrsRecorder {
    pub fn new() -> CaptrsRecorder {
        CaptrsRecorder { img: Vec::new() }
    }
}

impl Recorder for CaptrsRecorder {
    fn capture(&mut self) -> Result<crate::video::PixelProvider, Box<dyn Error>> {
        self.capturer.capture_store_frame();
        let (w, h) = self.capturer.geometry();
        self.img = self.capturer.get_stored_frame().unwrap();
        Ok(crate::video::PixelProvider::BGR0(w, h, &self.img))
    }
}
```



```
`NonNull<ID3D11Device>` cannot be sent between threads safely
within `CaptrsCapturable`, the trait `Send` is not implemented for `NonNull<ID3D11Device>`rustcE0277
main.rs(1, 1): required because it appears within the type `wio::com::ComPtr<ID3D11Device>`
main.rs(1, 1): required because it appears within the type `dxgcap::DuplicatedOutput`
main.rs(1, 1): required because it appears within the type `std::option::Option<dxgcap::DuplicatedOutput>`
main.rs(1, 1): required because it appears within the type `dxgcap::DXGIManager`
main.rs(1, 1): required because it appears within the type `Capturer`
captrs_capture.rs(7, 12): required because it appears within the type `CaptrsCapturable`
mod.rs(34, 23): required by a bound in `Capturable`
`NonNull<ID3D11DeviceContext>` cannot be sent between threads safely
within `CaptrsCapturable`, the trait `Send` is not implemented for `NonNull<ID3D11DeviceContext>`rustcE0277
main.rs(1, 1): required because it appears within the type `wio::com::ComPtr<ID3D11DeviceContext>`
main.rs(1, 1): required because it appears within the type `dxgcap::DuplicatedOutput`
main.rs(1, 1): required because it appears within the type `std::option::Option<dxgcap::DuplicatedOutput>`
main.rs(1, 1): required because it appears within the type `dxgcap::DXGIManager`
main.rs(1, 1): required because it appears within the type `Capturer`
captrs_capture.rs(7, 12): required because it appears within the type `CaptrsCapturable`
mod.rs(34, 23): required by a bound in `Capturable`
`NonNull<IDXGIOutput1>` cannot be sent between threads safely
within `CaptrsCapturable`, the trait `Send` is not implemented for `NonNull<IDXGIOutput1>`rustcE0277
main.rs(1, 1): required because it appears within the type `wio::com::ComPtr<IDXGIOutput1>`
main.rs(1, 1): required because it appears within the type `dxgcap::DuplicatedOutput`
main.rs(1, 1): required because it appears within the type `std::option::Option<dxgcap::DuplicatedOutput>`
main.rs(1, 1): required because it appears within the type `dxgcap::DXGIManager`
main.rs(1, 1): required because it appears within the type `Capturer`
captrs_capture.rs(7, 12): required because it appears within the type `CaptrsCapturable`
mod.rs(34, 23): required by a bound in `Capturable`
`NonNull<IDXGIOutputDuplication>` cannot be sent between threads safely
within `CaptrsCapturable`, the trait `Send` is not implemented for `NonNull<IDXGIOutputDuplication>`rustcE0277
main.rs(1, 1): required because it appears within the type `wio::com::ComPtr<IDXGIOutputDuplication>`
main.rs(1, 1): required because it appears within the type `dxgcap::DuplicatedOutput`
main.rs(1, 1): required because it appears within the type `std::option::Option<dxgcap::DuplicatedOutput>`
main.rs(1, 1): required because it appears within the type `dxgcap::DXGIManager`
main.rs(1, 1): required because it appears within the type `Capturer`
captrs_capture.rs(7, 12): required because it appears within the type `CaptrsCapturable`
mod.rs(34, 23): required by a bound in `Capturable`
weylus::capturable
pub trait Capturable
where
    Self: Send + BoxCloneCapturable,
```

2021-11-26 01:54 UTC, H-M-H commented
> My capturer implementation doesnt compile. Dont really know what to do about that. Its my first time really using rust ...

Don't worry :) The Capturable + Recorder traits are designed in such a way that the Capturable can be safely copied and shared among threads. So a Capturable should only store minimal meta information about what it is (in this case which display) and actually capturing the screen should be delegated to the Recorder which doesn't need to be cloneable or thread safe.

The concrete problem you have run into is that captrs Capturer is not thread safe. This means it "poisons" your CaptrsCapturable struct. The solution is to just store the display ID inside the Capturable and instantiate the Capturer only with the Recorder.

I hope this clears things up, gotta get some sleep now, so I will take some time to reply if something comes up.

2021-11-26 11:30 UTC, qdlmcfresh commented
the last thing missing now is a way to get the screensize from a capturable to calculate the coordinates. I thought about adding a screen_size function to the capturable trait but that wont work since in my case the recorder holds the captrs variable that has the screensize.

2021-11-26 12:19 UTC, H-M-H commented
Looks like captrs uses [`EnumOutputs`](https://docs.microsoft.com/en-us/windows/win32/api/dxgi/nf-dxgi-idxgiadapter-enumoutputs) instead of `EnumDisplayDevicesA` internally, which can be used to get the output geometry https://docs.microsoft.com/en-us/windows/win32/api/dxgi/nf-dxgi-idxgioutput-getdesc. If that does not work, a somewhat dirty solution is to just create a captrs capturer, query its geometry, save that and throw away the capturer immediately afterwards. Not exactly beautiful but sure better than nothing.

In the longrun I'd like to get rid of third party crates for screen capturing though as non of those (at least to my knowledge) provide a way to capture individual windows which is something I'd like to see supported on all platforms (actually only the Windows implementation is missing). But that's probably a significant amount of work and I understand if you are not up for it.

2021-11-26 19:48 UTC, qdlmcfresh commented
Another thing to look at is the coordinate offset. Sadly captrs implements a function to get the offset for linux but not for windows. The best thing i could get is this via [EnumDisplayMonitors](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-enumdisplaymonitors) and [GetMonitorInfo](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmonitorinfoa):
```
Monitor: 0
rcMonitor.left -1920 rcMonitor.top 0 rcMonitor.right 0 rcMonitor.bottom 1080
1080x1920
rcWork.left -1920 rcWork.top 0 rcWork.right 0 rcWork.bottom 1040
1040x1920
dwFlags: 0

Monitor: 1
rcMonitor.left 0 rcMonitor.top 0 rcMonitor.right 2560 rcMonitor.bottom 1440
1440x2560
rcWork.left 0 rcWork.top 0 rcWork.right 2560 rcWork.bottom 1400
1400x2560
dwFlags: 1
```
Calculating the offsets is weird though since: `rcMonitor.left * -1 + event.x` results in a correct coordinate for "Monitor 1" but i dont know how that maps to more monitors with different layouts than left->right. 
I dont think [dxgcap](https://github.com/bryal/dxgcap-rs/blob/009b746d1c19c4c10921dd469eaee483db6aa002/src/lib.rs#L268) has the offset information either because the structs returned by the directx calls seem very similar to the ones i get with GetMonitorInfo

I have a working setup for 1 monitor though :)

2021-11-26 21:20 UTC, H-M-H commented
> Sadly captrs implements a function to get the offset for linux but not for windows

Oh well, I looked into the docs and saw a `position` method but the docs are generated on a linux machine and it indeed looks like it's missing for windows...

But the good news is that it looks like directly calling winapi can solve this:
https://github.com/bryal/dxgcap-rs/blob/009b746d1c19c4c10921dd469eaee483db6aa002/src/lib.rs#L270-L275
As far as I can tell this is calling this method: https://docs.microsoft.com/en-us/windows/win32/api/dxgi/nf-dxgi-idxgioutput-getdesc which I mentioned earlier. It requires getting the displays through [EnumOutputs](https://docs.microsoft.com/en-us/windows/win32/api/dxgi/nf-dxgi-idxgiadapter-enumoutputs) though.

> Calculating the offsets is weird though since: rcMonitor.left * -1 + event.x results in a correct coordinate for "Monitor 1" but i dont know how that maps to more monitors with different layouts than left->right.

I wouldn't go there, that indeed sounds like different layouts would immediately break this.

> Btw this doesnt return the same order as the EnumMonitorDevices method. Main Display is 1 with EnumMonitorDevices and 0 with EnumDisplayDevicesA for whatever reason

I'd say getting `EnumOutputs` working instead of relying on the other two functions is the best option, even though it sadly looks like it's going to be a little more complicated.

> I have a working setup for 1 monitor though :)

Awesome, that's great progress!

2021-11-27 11:11 UTC, qdlmcfresh commented
You are right that using EnumDisplays will probably be the easiest way to get the RECT of each Monitor indexed in a way that captrs will understand. Thats not really my problem... Sorry if i failed to communicate that in my previous reply, i was in a rush when writing that.
So ill try again 😄 :
![grafik](https://user-images.githubusercontent.com/10837173/143678370-7f3174c9-e0b2-4658-a6a2-297ced67ac66.png)
This is one possible virtual screen layout. For winapi functions like mouse_event or SetCursorPos(x, y), the coordinate system in the picture is used. so (0,0) will end up to be the top left corner of the primary display and (0 - Monitor2.width, 0) will be the top left corner of Monitor2.  The RECT you get by GetMonitorInfo/iDXGIOUTPUT.getDesc will work perfectly fine for these functions since the RECT for Monitor2 will be 
```
{
left: -1 * (MON2_WIDTH)
top: 0
right: 0
bottom: MON2_HEIGHT
}
```
For InjectSyntheticPointerInput this is not the case though. [MSDN](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-injectsyntheticpointerinput): "The ptPixelLocation for each POINTER_TYPE_INFO is specified relative to top left of the virtual screen" So (0,0) will end up to be the top-left corner of Monitor2 in the picture above.

What im struggeling to wrap my head around is an easy way to calculate the actual coordinate of the top-left corner of each monitor on the virtualdisplay-coordinatesystem as its understood by InjectSyntheticPointerInput

2021-11-27 11:56 UTC, H-M-H commented
Oh, I see.
Are the values for bottom and top really correct in the example you gave for monitor 2, I'd expect some offset so it matches the picture.

If there is indeed some kind of offset the following should be correct: The coordinate systems only differ by a translation, so to go from getDesc to Virtual Screen you just need to subtract the minimal left value over all monitors as well as the minimal top value respectively for left and right, top and bottom of the monitor coordinates you want to convert.

2021-11-27 12:01 UTC, qdlmcfresh commented
> If there is indeed some kind of offset the following should be correct: The coordinate systems only differ by a translation, so to go from getDesc to Virtual Screen you just need to subtract the minimal left value over all monitors as well as the minimal top value respectively for left and right, top and bottom of the monitor coordinates you want to convert.

Yes i think thats right, i was testing just now and came up with this:
```cpp
    void print() {
        int i = 0;
        for (const RECT &r : this->rcMonitors) {
            std::printf("Monitor[%i] Left: %i Top: %i  Right: %i Bottom: %i\n", i++, r.left, r.top, r.right,r.bottom);
        }
        std::printf("Union: Left: %i Top: %i  Right: %i Bottom: %i\n", this->rcCombined.left , this->rcCombined.top, this->rcCombined.right, this->rcCombined.bottom );
        std::printf("\n\n");
        for (const RECT& r : this->rcMonitors) {
            std::printf("Monitor+Offset[%i] Left: %i Top: %i  Right: %i Bottom: %i \n", i++,r.left - rcCombined.left, r.top,  r.right + rcCombined.right, r.bottom);
        }   
    }
```
```
Monitor[0] Left: -1920 Top: 0  Right: 0 Bottom: 1080
Monitor[1] Left: 0 Top: 0  Right: 2560 Bottom: 1440
Monitor[2] Left: 0 Top: -1080  Right: 1920 Bottom: 0

Union: Left: -1920 Top: -1080  Right: 2560 Bottom: 1440

Monitor+Offset[0] Left: 0 Top: 0  Right: 2560 Bottom: 1080
Monitor+Offset[1] Left: 1920 Top: 0  Right: 5120 Bottom: 1440
Monitor+Offset[2] Left: 1920 Top: -1080  Right: 4480 Bottom: 0
```

2021-11-27 12:24 UTC, H-M-H commented
That's looking good, it appears top and bottom behave as I expected.

I do think instead of
```cpp
std::printf("Monitor+Offset[%i] Left: %i Top: %i  Right: %i Bottom: %i \n", i++,r.left - rcCombined.left, r.top,  r.right + rcCombined.right, r.bottom);
```
it should be
```cpp
std::printf("Monitor+Offset[%i] Left: %i Top: %i  Right: %i Bottom: %i \n", i++,r.left - rcCombined.left, r.top - rcCombined.top,  r.right - rcCombined.left, r.bottom - rcCombined.top);
```
though.

2021-11-27 13:48 UTC, qdlmcfresh commented
Ok cool i think we have this worked out. 
```rust
use std::mem::zeroed;
use std::{mem, ptr};
use winapi::shared::dxgi::{
    CreateDXGIFactory1, IDXGIAdapter1, IDXGIFactory1, IDXGIOutput, IID_IDXGIFactory1,
    DXGI_OUTPUT_DESC,
};

use winapi::shared::windef::*;
use winapi::shared::winerror::*;
use winapi::um::winuser::*;
use wio::com::ComPtr;

// from https://github.com/bryal/dxgcap-rs/blob/009b746d1c19c4c10921dd469eaee483db6aa002/src/lib.r
fn hr_failed(hr: HRESULT) -> bool {
    hr < 0
}

fn create_dxgi_factory_1() -> ComPtr<IDXGIFactory1> {
    unsafe {
        let mut factory = ptr::null_mut();
        let hr = CreateDXGIFactory1(&IID_IDXGIFactory1, &mut factory);
        if hr_failed(hr) {
            panic!("Failed to create DXGIFactory1, {:x}", hr)
        } else {
            ComPtr::from_raw(factory as *mut IDXGIFactory1)
        }
    }
}

fn get_adapter_outputs(adapter: &IDXGIAdapter1) -> Vec<ComPtr<IDXGIOutput>> {
    let mut outputs = Vec::new();
    for i in 0.. {
        unsafe {
            let mut output = ptr::null_mut();
            if hr_failed(adapter.EnumOutputs(i, &mut output)) {
                break;
            } else {
                let mut out_desc = zeroed();
                (*output).GetDesc(&mut out_desc);
                if out_desc.AttachedToDesktop != 0 {
                    outputs.push(ComPtr::from_raw(output))
                } else {
                    break;
                }
            }
        }
    }
    outputs
}

pub struct win_ctx {
    outputs: Vec<RECT>,
    union_rect: RECT,
}

impl win_ctx {
    pub fn new() -> win_ctx {
        let mut rects: Vec<RECT> = Vec::new();
        let mut union: RECT;
        unsafe {
            union = mem::zeroed();
            let factory = create_dxgi_factory_1();
            let mut adapter = ptr::null_mut();
            if factory.EnumAdapters1(0, &mut adapter) != DXGI_ERROR_NOT_FOUND {
                let adp = ComPtr::from_raw(adapter);
                let outputs = get_adapter_outputs(&adp);
                for o in outputs {
                    let mut desc: DXGI_OUTPUT_DESC = mem::zeroed();
                    o.GetDesc(ptr::addr_of_mut!(desc));
                    rects.push(desc.DesktopCoordinates);
                    UnionRect(
                        ptr::addr_of_mut!(union),
                        ptr::addr_of!(union),
                        ptr::addr_of!(desc.DesktopCoordinates),
                    );
                }
            }
        }
        win_ctx {
            outputs: rects,
            union_rect: union,
        }
    }
    pub fn get_outputs(&self) -> &Vec<RECT> {
        &self.outputs
    }
    pub fn get_union_rect(&self) -> &RECT {
        &self.union_rect
    }
}
```
Would it be possible give each of my `Capturables` a `win_ctx` that holds all the neccesary information and access it in my `InputDevice`?

2021-11-27 15:32 UTC, H-M-H commented
Looks like the input device needs to know about the window context too, so I guess it can't be helped but to lookup the dimensions of the Virtual Screen inside the input device with its own handle as well. Then the Capturables `geometry_relative` can be translated back to what `InjectSyntheticPointerInput` expects.

Perhaps a little explanation why I designed things like this: On Linux you can simulate inputs on a pretty low level with absolutely no knowledge of display sizes or positions. You can even declare your own (rectangular) input coordinate system which on some higher level is then mapped to actual screen coordinates. `InjectSyntheticPointerInput` lives on a higher level and is aware of the Virtual Screen and that's why things are getting a little awkward here.

2021-11-27 16:08 UTC, qdlmcfresh commented
It works now with multiple monitors, i edited the capturable trait though. I dont think thats the perfekt solution, but i wanted to see if the coordinate translation is correct before figuring the rest out

Just tell me what i have to change for it to get merged and i will try my best :)

2021-11-27 17:25 UTC, H-M-H commented
I'd say lets get it building everywhere, fixup the trait and then I will have a look again. Thanks for your work!

2021-11-29 11:01 UTC, qdlmcfresh commented
> I'd say lets get it building everywhere, fixup the trait and then I will have a look again. Thanks for your work!

Ragarding fixing up the trait. While researching the Box<dyn> pattern i found [this](https://bennetthardwick.com/dont-use-boxed-trait-objects-for-struct-internals/) post and if i understand it correctly this fits here. Since all of the Capturable implementations hold different data, that might be needed in the implementations of Input but there is no way to get back to the original struct after putting it in a box.

2021-11-29 12:49 UTC, H-M-H commented
How about a compromise, I still think `Box<dyn _>` makes sense here and I'd like to avoid leaking too much unnecessary details about the capturable. So what I think should work is to change the Capturable trait, so it has one `geometry` method that returns an enum of possible Geometries:
```rust
enum Geometry {
    Relative(f64, f64, f64, f64),
    VirtualScreen(i32, i32, u32, u32),
}
```
The VirtualScreen variant can then be marked `unreachable!()` on non windows systems.

2021-11-29 12:57 UTC, qdlmcfresh commented
Sounds good

2021-11-29 17:39 UTC, H-M-H requested changes
Alright, I've had a look now, actually already yesterday but I forgot to submit the review.

2021-11-29 17:39 UTC, H-M-H commented on src/capturable/mod.rs
> +    /// Or offset_x, offset_y, width, height for a capturable using a virtual screen. (Windows)
The docs should be moved to the geometry enum.

2021-11-29 17:39 UTC, H-M-H commented on src/capturable/x11.rs
> +    fn geometry(&self) -> Result<(Geometry), Box<dyn Error>> {
No braces here : `(Geometry)`.

2021-11-29 17:39 UTC, H-M-H commented on src/input/autopilot_device_win.rs
> +    fn send_keyboard_event(&mut self, event: &KeyboardEvent) {
General design: I'd prefer to use delegation here instead of copying the autopilot code. That means an instance of the AutoPilotDevice should live inside inside `self` so you can do `self.autopilot_device.send_keyboard_event` here.

2021-11-29 17:39 UTC, H-M-H commented on src/input/autopilot_device_win.rs
> +                match event.button {
I think this can be removed, button events are handled via `ButtonChangeType`, are they not?

2021-11-29 18:26 UTC, qdlmcfresh commented on src/input/autopilot_device_win.rs
> +                            dwTime: 0,
This doesnt work, dont know why

2021-11-29 18:28 UTC, qdlmcfresh commented on src/input/autopilot_device_win.rs
> +                match event.button {
Only for Stylus and Touch i think

2021-11-29 18:34 UTC, qdlmcfresh commented on src/capturable/captrs_capture.rs
> +        let _ = self.capturer.capture_store_frame();
The ? operator doesnt work here
```
the trait bound `CaptureError: StdError` is not satisfied
required because of the requirements on the impl of `std::convert::From<CaptureError>` for `Box<dyn StdError>`
required because of the requirements on the impl of `FromResidual<Result<Infallible, CaptureError>>` for `Result<PixelProvider<'_>, Box<dyn StdError>>`rustcE0277
try_trait.rs(339, 5): required by `from_residual`
```

2021-11-29 18:43 UTC, H-M-H commented on src/capturable/captrs_capture.rs
> +        let _ = self.capturer.capture_store_frame();
Oh, wow, CaptureError doesn't implement the Error trait, I did not expect that... I guess that calls for a wrapper like:
https://github.com/H-M-H/Weylus/blob/e23d3b9133abbe7e43e27b15aecfa436158b8033/src/capturable/pipewire.rs#L32-L42

2021-11-29 18:44 UTC, qdlmcfresh commented on src/input/autopilot_device_win.rs
> +                    | POINTER_FLAG_PRIMARY
The pointerflags should be pretty much the same for stylus and touch i think
![grafik](https://user-images.githubusercontent.com/10837173/143924627-dc2be5f4-9a05-4d7b-a02d-4a4297d9321e.png)
from [mdsdocs](https://docs.microsoft.com/de-de/windows/win32/api/winuser/nf-winuser-injecttouchinput)

But touch input doesnt work anyways. Will have to look into this more

2021-11-29 18:45 UTC, H-M-H commented on src/input/autopilot_device_win.rs
> +                            dwTime: 0,
I think this is because different clocks are used, you'd probably need to do some research into whether it's feasible to convert one into the other. This is a nice to have though and not blocking a merge.

2021-11-29 18:47 UTC, H-M-H commented on src/input/autopilot_device_win.rs
> +                match event.button {
Is it a bad idea to simulate the mouse via `InjectSyntheticPointerInput`, I'd prefer to completely remove the autopilot dependency in the long run?

2021-11-29 18:50 UTC, qdlmcfresh commented on src/input/autopilot_device_win.rs
> +                match event.button {
Dont know if that is possible, since [CreateSyntheticPointerDevice](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createsyntheticpointerdevice) only supports PT_PEN and PT_TOUCH.
We could use winapi instead of autopilot though

2021-11-29 18:52 UTC, H-M-H commented on src/input/autopilot_device_win.rs
> +                match event.button {
That'd be nice!

2021-11-29 19:01 UTC, H-M-H commented on src/capturable/captrs_capture.rs
> +        let _ = self.capturer.capture_store_frame();
Just opened an issue over at https://github.com/bryal/captrs/issues/9

2021-11-29 19:21 UTC, qdlmcfresh commented on src/capturable/captrs_capture.rs
> +        let _ = self.capturer.capture_store_frame();
Either i did the error maping wrong or this happens quite often
```
2021-11-29T19:19:48.724225Z  WARN weylus::websocket: Error capturing screen: Captrs failed to capture frame
2021-11-29T19:19:49.219993Z  WARN weylus::websocket: Error capturing screen: Captrs failed to capture frame
2021-11-29T19:19:49.728879Z  WARN weylus::websocket: Error capturing screen: Captrs failed to capture frame
2021-11-29T19:19:52.066042Z  WARN weylus::websocket: Error capturing screen: Captrs failed to capture frame
2021-11-29T19:19:52.899031Z  WARN weylus::websocket: Error capturing screen: Captrs failed to capture frame
```

2021-11-29 19:24 UTC, qdlmcfresh commented
To get windowcapture working ill look into this sometime https://github.com/robmikh/screenshot-rs

2021-11-30 18:54 UTC, H-M-H commented
Alright, what's still missing? Touch support needs to be figured out and I suspect general fine tuning and checking edge cases has to be done. Do you want to include window capturing in this pull request?

Also once you are confident enough, we can try to summon some testers from the original issue :)

2021-11-30 19:01 UTC, qdlmcfresh commented
Yes injecting touch is weird and i cant really find good resources. Only thing i got to work in my c++ tests was a tap but motion is just not working.

I think window capturing will also have to wait :)

Since drawing works fine (on my side) go ahead and summon the testers so we can see what works and what doesnt 😄

2021-11-30 19:21 UTC, H-M-H commented
> Yes injecting touch is weird and i cant really find good resources.

Touch input was also rather difficult to figure out on Linux, consider your suffering shared :P

Also, one other thing I completely forgot to mention: This project has an explicit CLA: https://github.com/H-M-H/Weylus/blob/master/CONTRIBUTORS

Please add yourself to the list (that is if you agree with the license).

2021-11-30 19:32 UTC, qdlmcfresh commented
> > Yes injecting touch is weird and i cant really find good resources.
> 
> Touch input was also rather difficult to figure out on Linux, consider your suffering shared :P
> 
Well thats something haha 😅 
> Also, one other thing I completely forgot to mention: This project has an explicit CLA: https://github.com/H-M-H/Weylus/blob/master/CONTRIBUTORS
> 
> Please add yourself to the list (that is if you agree with the license).
Seems reasonable :)

2021-12-02 11:20 UTC, qdlmcfresh commented
Got touch working for 1 finger. How do you handle multitouch on linux? I saw there is another [API](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events) for TouchEvents that sends a TouchList for a group of touches.

2021-12-02 11:35 UTC, H-M-H commented
Touch is also handled via `PointerEvents` as these are intended as unified API for all kinds of input. `event.event_type` and `event.pointer_id` can be used to keep track of individual fingers. On Linux I manually keep tack of active `pointer_id`s as I need to map them to the five touch input slots.

2021-12-02 11:40 UTC, qdlmcfresh commented
> Touch is also handled via `PointerEvents` as these are intended as unified API for all kinds of input. `event.event_type` and `event.pointer_id` can be used to keep track of individual fingers. On Linux I manually keep track of active `pointer_id`s as I need to map them to the five touch input slots.

Ah ok thats what i thought, saw the pointer_ids change in the debug messages ... sounds cumbersome 🤓

2021-12-02 11:50 UTC, H-M-H commented
If you need to keep track of them on your own, it is. But perhaps the Windows API already does that for you?

2021-12-02 12:08 UTC, qdlmcfresh commented
If i understand it correctly you have to create an array of [POINTER_TOUCH_INFOs](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-pointer_touch_info) to call [InjectTouchInput](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-injecttouchinput) with mutliple contact points

2021-12-02 12:14 UTC, qdlmcfresh commented
Btw InjectTouchInput takes the same coordinates as mouse_event again... 
WindowsAPI is great! \s

2021-12-02 12:19 UTC, H-M-H commented
Hmm, can't you just use `InjectSyntheticPointerInput` for touch events as well?

2021-12-02 12:21 UTC, qdlmcfresh commented
Should be possible but as i said before thats just not workig somehow. I was surprised InjectTouchInput is working as expected 😅

2021-12-02 12:29 UTC, qdlmcfresh commented
Omfg I figured it out... For touchinput to work with InjectSyntheticPointerInput you have to call InitializeTouchInjection first. This is also true for InjectTouchInput but never mentioned in the docs for InjectSyntheticPointerInput

2021-12-21 18:37 UTC, H-M-H commented
Any progress regarding touch input? Can I help somehow?

2021-12-21 22:45 UTC, qdlmcfresh commented
Sry dont have too much spare time at the moment. The only thing missing regarding touch input is correct handling of multitouch. I do get multiple pointers for multiple fingers but they dont work together. Another thing i had a deeper look at was [this](https://github.com/robmikh/displayrecorder ). I was able to confirm that window-capturing is possible like its done there, but i wasnt able to integrate it with weylus yet.

2021-12-22 00:03 UTC, H-M-H commented
Thanks for the update!

> Sry dont have too much spare time at the moment

Nothing to worry about, I mean we all do this in our spare time. Also have a merry Christmas :christmas_tree:!

2021-12-22 09:32 UTC, qdlmcfresh commented
> Nothing to worry about, I mean we all do this in our spare time. Also have a merry Christmas 🎄!
Thank you 😃, have nice holidays aswell 🎅

2022-01-05 12:41 UTC, qdlmcfresh commented
First of all happy new year! :) Regarding diplay and window capture again. I asked the author of  [displayrecorder](https://github.com/robmikh/displayrecorder/)and screenshot-rs if its is possible to get a unencoded frame the way hes capturing in displayrecorder [here](https://github.com/robmikh/displayrecorder/issues/5). The answer was sadly, no. But since hes using mediafoundation aswell maybe this could still be usefull. I just donk know enough about directx and mediafoundation to judge that.

2022-03-24 14:34 UTC, H-M-H commented
@qdlmcfresh how's this going, will you have time in the foreseeable future? If not, perhaps somebody else using Windows as well is willing to take this over and get multi touch working.

2022-05-28 11:42 UTC, qdlmcfresh commented
Since @Ph-Fr-One is no longer with us i took the liberty to integrate his changes into this PR. I tested with 2 screens on Win10 and zoom/pinch gestures are working fine.

2022-09-17 15:47 UTC, aegistudio commented
I've seen that captrs is constantly reporting `CaptureError::Timeout` when I am using. I've tried tweaking it by specifying a timeout (e.g. `Capturer::new_with_timeout(id.into(), Duration::from_millis(1000))`) but it did not work for me.

Are these just some expected and okay-to-ignore errors when working with captrs, or do I need some further configurations?

2022-09-17 16:46 UTC, aegistudio commented
And I do want to mention that the pen input seem not to be tilting towards the right direction. I've tried orientate the tablet in the landscape and vertical directions, both rendering the pen tilting wrongly.

https://user-images.githubusercontent.com/6104287/190867550-9c6da247-1595-4ea9-b0d6-2e373bf735e3.mp4

https://user-images.githubusercontent.com/6104287/190867551-6521e387-3ca4-4dfc-9365-467f4c61ae5d.mp4

2023-03-01 21:59 UTC, flomorky commented
Hello hello guys i'v just read your topic and it soo cool, but im little pickle with all does stuff and I don't understand any of it. i'm trying to understand it but its hard. So did you finally manage to add pointer movment with weylus ? I would really love to use it if you could show me how to install it. Cause I got now but it does not work with pen sensivity of my Ipad :/

2023-03-02 08:44 UTC, qdlmcfresh commented
> Hello hello guys i'v just read your topic and it soo cool, but im little pickle with all does stuff and I don't understand any of it. i'm trying to understand it but its hard. So did you finally manage to add pointer movment with weylus ? I would really love to use it if you could show me how to install it. Cause I got now but it does not work with pen sensivity of my Ipad :/

https://github.com/kotaewing/Weylus/releases/tag/V1.1 should be a build with the changes in this PR integrated.

2023-03-02 13:30 UTC, flomorky commented
Wow thats super man thanks ! Now the only thing would be to add a wired
connection to it so there will be no latency. Its like almost the perfect
software but trying to sketch on Photoshop with it is a bit tricky with the
delay

Le jeu. 2 mars 2023, 03 h 44, qdlmcfresh ***@***.***> a
écrit :

> Hello hello guys i'v just read your topic and it soo cool, but im little
> pickle with all does stuff and I don't understand any of it. i'm trying to
> understand it but its hard. So did you finally manage to add pointer
> movment with weylus ? I would really love to use it if you could show me
> how to install it. Cause I got now but it does not work with pen sensivity
> of my Ipad :/
>
> https://github.com/kotaewing/Weylus/releases/tag/V1.1 should be a build
> with the changes in this PR integrated.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/H-M-H/Weylus/pull/128#issuecomment-1451499725>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6G24TG2SIQDM3G7IJCNPVLW2BMXZANCNFSM5IZEFYBQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-06-15 20:49 UTC, digitalsignalperson commented
I got this to build with the hhmhh/weylus_build docker image by
- extracting ffmpeg-n6.0-latest-win64-gpl-shared-6.0.zip from https://github.com/BtbN/FFmpeg-Builds into /Weylus/deps/dist_windows
- it doesn't include libx264 though, so grabbed libx264_0.164.r3107_msvc17.zip from https://github.com/ShiftMediaProject/x264/releases

```
docker run -it hhmhh/weylus_build bash
git clone https://github.com/qdlmcfresh/Weylus.git -b stylus_windows

# from host
docker cp ~/x/ffmpeg-n6.0-latest-win64-gpl-shared-6.0/. 878bc718f089:/Weylus/deps/dist_windows/.
docker cp ~/x/libx264_0.164.r3107_msvc17/bin/x64/x264.dll 878bc718f089:/Weylus/deps/dist_windows/bin/
docker cp ~/x/libx264_0.164.r3107_msvc17/include/x264.h 878bc718f089:/Weylus/deps/dist_windows/include/
docker cp ~/x/libx264_0.164.r3107_msvc17/include/x264_config.h 878bc718f089:/Weylus/deps/dist_windows/include/
docker cp ~/x/libx264_0.164.r3107_msvc17/lib/x64/libx264.lib 878bc718f089:/Weylus/deps/dist_windows/lib/
docker cp ~/x/libx264_0.164.r3107_msvc17/lib/x64/x264.lib 878bc718f089:/Weylus/deps/dist_windows/lib/

# in container
cargo build --target x86_64-pc-windows-gnu --release

# from host
docker cp 878bc718f089:/Weylus/target/x86_64-pc-windows-gnu/release/weylus.exe ~/x/
```

Also for weylus.exe to work I had to bundle it with all the dll files from the bin folders from those zips.

Very cool this works.

2023-06-15 21:35 UTC, digitalsignalperson commented
Does this work for anyone with server = windows, client = linux? If not I bet it'd be pretty close based on this work so far.

For me I can do windows to windows, but when I try remoting to a windows machine from linux, the stylus events don't show up on the windows side. And I can confirm with `libinput debug-events` that I do have stylus events on the linux source.

This would be super awesome to have a weylus server in a windows VM and be able to use the stylus from a a linux host. I don't think there's any other solution right now to do linux -> windows stylus stuff. If anyone knows of anything I'd love to hear. 

For windows to windows, RDP already supports pen & pressure and touch. But this isn't implemented in freerdp yet https://github.com/FreeRDP/FreeRDP/issues/7260

2023-06-15 23:01 UTC, digitalsignalperson commented
I also just tested that windows <--> windows RDP shadowing work with the pen and pressure too. Shadowing is screen is mirrored on both sides without RDP taking over, so very similar to this PR but built into windows. Also unfortunately this is not implemented in freerdp for linux --> windows https://github.com/FreeRDP/FreeRDP/issues/5656

To try the rdp shadowing, see group policy for Computer Configuration -> Administrative Templates -> Windows components -> Remote Desktop Services -> Remote Session Host -> Connections -> Set rules for remote control of Remote Desktop Services user sessions

and then 

```
mstsc /shadow:1 /v:192.168.0.xx /prompt /noConsentPrompt /control
```

I'll try to look at the linux --> windows possibilities with this PR later

2024-09-25 16:24 UTC, merged